apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  namespace: ageiport
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - image: mysql
          name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: password
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          hostPath:
            path: /Users/lingyi/k8s-volumes/data/mysql-persistent-storage
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: ageiport
  labels:
    app: mysql
spec:
  type: NodePort
  ports:
    - port: 3306
      protocol: TCP
      targetPort: 3306
      name: mysql
  selector:
    app: mysql

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: ageiport
  name: ingress-nginx
spec:
  rules:
    - host: mysql.alibaba-ageiport.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mysql
                port:
                  number: 3306