apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgsql
  namespace: ageiport
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgsql
  template:
    metadata:
      labels:
        app: pgsql
    spec:
      containers:
        - name: pgsql
          image: postgres:14
          env:
            - name: POSTGRES_USER
              value: root
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_DB
              value: pgsql
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: pgsql-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: pgsql-data
          hostPath:
            path: /Users/lingyi/k8s-volumes/data/pgsql
---
apiVersion: v1
kind: Service
metadata:
  name: pgsql
  namespace: ageiport
  labels:
    app: pgsql
spec:
  type: ClusterIP
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: pgsql

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: ageiport
  name: ingress-nginx
spec:
  rules:
    - host: pgsql.alibaba-ageiport.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pgsql
                port:
                  number: 5432