apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgsql
  namespace: ageiport
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgsql
  template:
    metadata:
      labels:
        app: pgsql
    spec:
      containers:
        - name: pgsql
          image: postgres:14
          env:
            - name: POSTGRES_USER
              value: root
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_DB
              value: pgsql
            - name: TZ
              value: Asia/Shanghai
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: pgsql-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: pgsql-data
          hostPath:
            path: /Users/lingyi/k8s-volumes/data/pgsql
---
apiVersion: v1
kind: Service
metadata:
  name: pgsql
  namespace: ageiport
  labels:
    app: pgsql
spec:
  type: NodePort
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
    nodePort: 30001
  selector:
    app: pgsql
