server:
  port: 8769

spring:
  application:
    name: ageiport-eureka-client

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka.alibaba-ageiport.com/eureka/ #Eureka地址
ageiport:
    taskServerClientOptions:
        port: 80
        endpoint: ageiport-task-server.alibaba-ageiport.com