server:
  port: 8769

spring:
  application:
    name: ageiport-eureka-client

eureka:
  instance:
    instance-id: ${spring.application.name}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/ #Eureka地址